const houseplantList = [
    {
        i: 0,
        name: "Aluminum Plant",
        botanical_name: "Pilea cadierei",
        type: "Foliage",
        origin: "Vietnam",
        watering: "1-2 times a week",
        soil: "Peat moss based potting mix with added perlite for faster drainage",
        propagation: "Stem cutting",
        height: "12-18 inches / 30-45 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 1,
        name: "Anthurium",
        botanical_name: "Anthurium clarinervium",
        type: "Foliage",
        origin: "Southern Mexico and Central America",
        watering: "2 times a week",
        soil: "Fast-draining acidic potting mix",
        propagation: "Stem cutting",
        height: "2 ft / 60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 2,
        name: "Areca Palm Tree",
        botanical_name: "Dypsis lutescens",
        type: "Foliage",
        origin: "Madagascar",
        watering: "Every 10 days",
        soil: "Mix 2 peat moss-based potting mix and 1 horticultural sand",
        propagation: "Offshoots / Seeds",
        height: "6-8 ft / 1.8-2.4 m",
        temperature: "70-85°F / 21-27°C",
        humidity: "40-50%",
    },
    {
        i: 3,
        name: "Arrowhead Plant",
        botanical_name: "Syngonium podophyllum",
        type: "Foliage",
        origin: "South America",
        watering: "Every 10-14 days",
        soil: "Peat-moss based potting mix with added perlite and/or vermiculite for good drainage",
        propagation: "Stem cutting",
        height: "2-4 ft / 0.6-1.2 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "40-50%",
    },
    {
        i: 4,
        name: "Asparagus Fern",
        botanical_name: 'Asparagus densiflorus "Sprengeri"',
        type: "Foliage",
        origin: "South Africa",
        watering: "Every 7-14 days",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Offshoots / Seeds",
        height: "3 ft / 90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "Around 40%",
    },
    {
        i: 5,
        name: "Baby Rubber Plant",
        botanical_name: "Peperomia obtusifolia",
        type: "Foliage",
        origin: "South America",
        watering: "Every 7-14 days",
        soil: "African violet potting mix",
        propagation: "Stem cutting",
        height: "10 in / 25 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 6,
        name: "Baby's Tears",
        botanical_name: "Soleirolia soleirolii",
        type: "Foliage",
        origin: "Western Mediterranean, Corsica and Sardinia",
        watering: "Every 5-7 days",
        soil: "African violet potting mix",
        propagation: "Division",
        height: "6 in / 15 cm",
        temperature: "60-75°F / 16-24°C",
        humidity: "50%",
    },
    {
        i: 7,
        name: "Bird's Nest Fern",
        botanical_name: "Asplenium nidus",
        type: "Foliage",
        origin: "Southeast Asia and Tropical Australia",
        watering: "Every 7-14 days",
        soil: "African violet potting mix",
        propagation: "Spores",
        height: "2 ft /  60 cm",
        temperature: "60-75°F / 16-24°C",
        humidity: "50%",
    },
    {
        i: 8,
        name: "Blushing Philodendron",
        botanical_name: "Philodendron erubescens",
        type: "Foliage",
        origin: "Colombia",
        watering: "2-3 times a week",
        soil: "African violet potting mix",
        propagation: "Stem cutting",
        height: "6 ft / 1.8 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "45%",
    },
    {
        i: 9,
        name: "Boston Fern",
        botanical_name: "Nephrolepsis exaltata",
        type: "Foliage",
        origin: "Florida, West Indies, Mexico, Central America, South America",
        watering: "2 times a week",
        soil: "African violet potting mix / Half-half mixture of peat moss and all-purpose potting mix",
        propagation: "Division",
        height: "1-3 ft / 30-90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 10,
        name: "Brake Fern",
        botanical_name: "Pteris cretica",
        type: "Foliage",
        origin: "Southern Mediterranean",
        watering: "Every 5-8 days",
        soil: "Any good-quality potting mix with added perlite for good drainage",
        propagation: "Division",
        height: "6 in to 2 ft / 15-60 cm",
        temperature: "60-70°F / 16-21°C",
        humidity: "50%",
    },
    {
        i: 11,
        name: "Button Fern",
        botanical_name: "Pellaea rotundifolia",
        type: "Foliage",
        origin: "New Zealand",
        watering: "Every 7 days",
        soil: "Peat moss based potting mix with added perlite or sand to help drainage",
        propagation: "Division",
        height: "1 ft / 30 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40-50%",
    },
    {
        i: 12,
        name: "Caladium",
        botanical_name: "Caladium x hortulanum",
        type: "Foliage",
        origin: "South America",
        watering: "Every 7 days",
        soil: "Peat moss-based potting mix",
        propagation: "Division",
        height: "2 ft / 60 cm",
        temperature: "75-80°F / 24-27°C",
        humidity: "50%",
    },
    {
        i: 13,
        name: "Calathea Orbifolia",
        botanical_name: "Calathea orbifolia",
        type: "Foliage",
        origin: "South America",
        watering: "Every 9 days",
        soil: "African violet potting mix",
        propagation: "Division",
        height: "2 ft / 60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "60%",
    },
    {
        i: 14,
        name: "Calathea Pinstripe",
        botanical_name: "Calathea ornata",
        type: "Foliage",
        origin: "Colombia, South America",
        watering: "Every 7-14 days",
        soil: "African violet mix",
        propagation: "Leaf cuttings",
        height: "2 ft / 60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "60-70%",
    },
    {
        i: 15,
        name: "Calathea Rattlesnake Plant",
        botanical_name: "Calathea lancifolia",
        type: "Foliage",
        origin: "Brazil",
        watering: "1-2 times a week",
        soil: "African violet potting mix",
        propagation: "Division",
        height: "2 ft / 60 cm",
        temperature: "70-85°F / 21-29°C",
        humidity: "50%",
    },
    {
        i: 16,
        name: "Calathea Roseopicta Corona",
        botanical_name: 'Calathea Roseopicta "Corona"',
        type: "Foliage",
        origin: "Central America and Brazil",
        watering: "Every 9 days",
        soil: "African violet mix",
        propagation: "Division",
        height: "18 in / 45 cm",
        temperature: "65-85°F / 18-29°C",
        humidity: "50%",
    },
    {
        i: 17,
        name: "California Pitcher Plant",
        botanical_name: "Darlingtonia californica",
        type: "Foliage",
        origin: "Northern California and Oregon, U.S.A.",
        watering: "Every 9 days",
        soil: "Nutrient-poor medium soil / Mix 1 part peat moss with 1 part perlite or horticultural sand",
        propagation: "Division",
        height: "12 in / 30 cm",
        temperature: "60-75°F / 16-24°C",
        humidity: "40%",
    },
    {
        i: 18,
        name: "Cape Sundew",
        botanical_name: "Drosera capensis",
        type: "Foliage",
        origin: "Subtropical Cape region of South Africa",
        watering: "2-3 times a week",
        soil: "Live sphagnum moss / A half-and-half mix of peat moss and horticultural sand",
        propagation: "Seeds / Division",
        height: "3 in / 8 cm",
        temperature: "60-75°F / 16-24°C",
        humidity: "50%",
    },
    {
        i: 19,
        name: "Cardboard Palm",
        botanical_name: "Zamia furfuracea",
        type: "Foliage",
        origin: "Eastern Mexico",
        watering: "2-3 times a week",
        soil: "Equal parts good-quality potting mix and sand for good drainage",
        propagation: "Seeds",
        height: "6 ft / 1.8 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 20,
        name: "Cast Iron Plant",
        botanical_name: "Aspidistra elatior",
        type: "Foliage",
        origin: "China, Japan",
        watering: "Every 9 days",
        soil: "All-purpose potting mix",
        propagation: "Division",
        height: "2-3 ft / 60-90 cm",
        temperature: "50-85°F / 10-29°C",
        humidity: "40%",
    },
    {
        i: 21,
        name: "Cat Palm Tree",
        botanical_name: "Chamaedorea cataractarum",
        type: "Foliage",
        origin: "Southern Mexico",
        watering: "Every week",
        soil: "Mix 1 part sand to 3 parts African violet mix",
        propagation: "Seeds",
        height: "6 ft / 1.8 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 22,
        name: "China Doll Plant",
        botanical_name: "Radermachera sinica",
        type: "Foliage",
        origin: "China, Taiwan",
        watering: "Every 9 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "4 ft / 1.2 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 23,
        name: "Chinese Evergreen",
        botanical_name: "Aglaonema commutatum",
        type: "Foliage",
        origin: "Subtropical forests of Southeast Asia",
        watering: "Every 5-10 days",
        soil: "Good-quality, all-purpose houseplant potting mix",
        propagation: "Stem cuttings",
        height: "2-3 ft / 60-90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 24,
        name: "Chinese Money Plant",
        botanical_name: "Pilea peperomioides",
        type: "Foliage",
        origin: "West Indies",
        watering: "Every 7-14 days",
        soil: "Good-quality peat moss-based potting mix",
        propagation: "Stem cuttings",
        height: "12 in / 30 cm",
        temperature: "65-85°F / 18-29°C",
        humidity: "40%",
    },
    {
        i: 25,
        name: "Clubmoss",
        botanical_name: "Selaginella kraussiana",
        type: "Foliage",
        origin: "South Africa",
        watering: "Every week",
        soil: "Peat moss-based potting mix with perlite or horticultural sand added for good drainage",
        propagation: "Division / Stem cuttings",
        height: "2-6 in / 5-15 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 26,
        name: "Coffee Plant",
        botanical_name: "Coffea arabica",
        type: "Foliage",
        origin: "Ethiopia",
        watering: "Every 1-2 weeks",
        soil: "Peat moss based potting mix with horticultural sand added to provide good drainage",
        propagation: "Seeds / Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 27,
        name: "Coleus Plant",
        botanical_name: "Coleus blumei",
        type: "Foliage",
        origin: "Southeast Asia",
        watering: "Every 9 days",
        soil: "Any good-quality, all-purpose potting mix ",
        propagation: "Seeds / Stem cutting",
        height: "2 ft / 60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 28,
        name: "Copper Plant",
        botanical_name: "Acalypha wilkesiana",
        type: "Foliage",
        origin: "Southwestern Pacific Islands",
        watering: "1-2 times a week",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 29,
        name: "Coral Bead Plant",
        botanical_name: "Nertera granadensis",
        type: "Foliage",
        origin: "New Zealand, Eastern Australia, Southeast Asia and South America ",
        watering: "Every week",
        soil: "2 parts peat moss-based potting mix with 1 part horticultural sand or perlite for good drainage",
        propagation: "Division / Seeds / Stem cuttings",
        height: "3 in / 8 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 30,
        name: "Corn Plant",
        botanical_name: "Dracaena fragrans",
        type: "Foliage",
        origin: "Tropical East Africa",
        watering: "Every 7-10 days",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "65-75°F / 18-24°C ",
        humidity: "40-50%",
    },
    {
        i: 31,
        name: "Creeping Fig",
        botanical_name: "Ficus pumila",
        type: "Foliage",
        origin: "China, Japan",
        watering: "Every week",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "3 ft / 90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 32,
        name: "Croton or Joseph's Coat",
        botanical_name: "Codiaeum variegatum",
        type: "Foliage",
        origin: "Pacific Islands, Malaysia, Northern Australia",
        watering: "Every week",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "3 ft / 90 cm",
        temperature: "65-85°F / 18-29°C",
        humidity: "60%",
    },
    {
        i: 33,
        name: "Dragon Tree",
        botanical_name: "Dracaena marginata",
        type: "Foliage",
        origin: "Madagascar",
        watering: "Every week",
        soil: "Good-quality, all-purpose houseplant potting mix",
        propagation: "Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 34,
        name: "Dumb Cane",
        botanical_name: "Dieffenbachia",
        type: "Foliage",
        origin: "Brazil",
        watering: "1-2 times a week",
        soil: "Peat moss-based potting mix with added perlite to allow good drainage",
        propagation: "Stem cuttings",
        height: "1-6 ft / 30 cm - 1.8 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 35,
        name: "Elephant's Ear",
        botanical_name: "Alocasia amazonica",
        type: "Foliage",
        origin: "Tropical Asia",
        watering: "Every 2-7 days",
        soil: "African violet potting mix",
        propagation: "Division",
        height: "2 ft / 60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 36,
        name: "English Ivy",
        botanical_name: "Hedera helix",
        type: "Foliage",
        origin: "Europe",
        watering: "Every week",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "20-30 ft / 6.1-9.1 m",
        temperature: "50-75°F / 10-24°C",
        humidity: "40%",
    },
    {
        i: 37,
        name: "European Fan Palm",
        botanical_name: "Chamaerops humilis",
        type: "Foliage",
        origin: "Mediterranean region of Southwestern Europe (Spain, Portugal, France, Italy and Malta)",
        watering: "Every week",
        soil: "Mix 2 parts peat moss-based potting mix and 1 part sharp sand",
        propagation: "Seeds",
        height: "4 ft / 1.2 m",
        temperature: "70-80°F / 21-27°C",
        humidity: "40%",
    },
    {
        i: 38,
        name: "False Aralia",
        botanical_name: "Dizygotheca elegantissima",
        type: "Foliage",
        origin: "South Pacific",
        watering: "Every week",
        soil: "All-purpose houseplant potting mix",
        propagation: "Seeds / Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "65-85°F / 18-29°C",
        humidity: "50%",
    },
    {
        i: 39,
        name: "Fiber Optic Grass",
        botanical_name: "Isolepis cernua",
        type: "Foliage",
        origin: "Western and Southern Europe, British Isles, North Africa, The West Coast of North America, Australia, New Zealand",
        watering: "Every 2 days",
        soil: "African violet potting mix",
        propagation: "Seeds / Division",
        height: "1 ft / 30 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40%",
    },
    {
        i: 40,
        name: "Ficus Alii",
        botanical_name: 'Ficus binnendiijkii "Alii"',
        type: "Foliage",
        origin: "South East Asia, India, China",
        watering: "Every 5-7 days",
        soil: "Good-quality potting mix",
        propagation: "Stem cuttings / Air layering",
        height: "10 ft / 3 m",
        temperature: "65-75°F / 18-24°C.",
        humidity: "40-50%",
    },
    {
        i: 41,
        name: "Fiddle Leaf Fig",
        botanical_name: "Ficus lyrata",
        type: "Foliage",
        origin: "Western Africa",
        watering: "Every 7-10 days",
        soil: "Good-quality all-purpose houseplant potting mix with added perlite for faster drainage",
        propagation: "Stem cuttings / Air layering",
        height: "3-10 ft / 90 cm - 3 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "40-50%",
    },
    {
        i: 42,
        name: "Fire Flash",
        botanical_name: "Chlorophytum orchidastrum",
        type: "Foliage",
        origin: "Tropical East Africa",
        watering: "Every 9 days",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Divisiom",
        height: "1-2 ft / 30-60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 43,
        name: "Fishtail Palm",
        botanical_name: "Caryota mitis",
        type: "Foliage",
        origin: "Tropical Asia from India to Java to southern China",
        watering: "Every week",
        soil: "All-purpose, good-quality potting mix. Use a ratio of 3:1 potting mix to horticultural sand",
        propagation: "Seeds / Offsets",
        height: "1 ft / 30 cm",
        temperature: "85°F /2 9°C ",
        humidity: "50%",
    },
    {
        i: 44,
        name: "Foxtail Fern",
        botanical_name: 'Asparagus densiflorus "Myers"',
        type: "Foliage",
        origin: "South Africa",
        watering: "Every week",
        soil: "All-purpose, good-quality potting mix",
        propagation: "Division",
        height: "3 ft / 90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40-50%",
    },
    {
        i: 45,
        name: "Friendship Plant",
        botanical_name: "Pilea involucrata",
        type: "Foliage",
        origin: "Central and South America",
        watering: "Every 9 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "12 in / 30 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 46,
        name: "Gold Dust Plant",
        botanical_name: "Aucuba japonica",
        type: "Foliage",
        origin: "Japan, China",
        watering: "Every week",
        soil: "All-purpose houseplant potting mix",
        propagation: "Seeds / Stem cuttings",
        height: "3 ft / 90 cm",
        temperature: "45-65°F / 7-18°C",
        humidity: "40%",
    },
    {
        i: 47,
        name: "Grape Ivy",
        botanical_name: "Cissus rhombifolia",
        type: "Foliage",
        origin: "South America",
        watering: "Every 5-7 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "2 ft / 60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40-60%",
    },
    {
        i: 48,
        name: "Heartleaf Philodendron",
        botanical_name: "Philodendron scandens",
        type: "Foliage",
        origin: "South America",
        watering: "Every 1-2 weeks",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "4 ft / 1.2 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 49,
        name: "Holly Fern",
        botanical_name: "Cyrtomium falcatum",
        type: "Foliage",
        origin: "Japan and China",
        watering: "Every week",
        soil: "Good-quality, all-purpose houseplant potting mix",
        propagation: "Division",
        height: "2 ft / 60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 50,
        name: "Inch Plant",
        botanical_name: "Tradescantia zebrina",
        type: "Foliage",
        origin: "Mexico and South America",
        watering: "Every 9 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "2 ft / 60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "45%",
    },
    {
        i: 51,
        name: "Iresine",
        botanical_name: "Iresine herbstii",
        type: "Foliage",
        origin: "Brazil",
        watering: "Every 9 days",
        soil: "Any good-quality, all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "2 ft / 60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 52,
        name: "Iron Cross Begonia",
        botanical_name: "Begonia masoniana",
        type: "Foliage",
        origin: "Southeast Asia",
        watering: "Every 3-4 weeks",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "1 ft / 30 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 53,
        name: "Janet Craig Dracaena",
        botanical_name: "Dracaena deremensis",
        type: "Foliage",
        origin: "East Africa",
        watering: "Every 10-14 days",
        soil: "Any good-quality potting mix",
        propagation: "Stem cuttings",
        height: "10 ft / 3 m",
        temperature: "65-75°F/18-24°C",
        humidity: "40-50%",
    },
    {
        i: 54,
        name: "Japanese Aralia",
        botanical_name: "Fatsia japonica",
        type: "Foliage",
        origin: "Southern Japan, Southern Korea",
        watering: "Every week",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "60-65°F / 16-18°C",
        humidity: "45%",
    },
    {
        i: 55,
        name: "Jerusalem Cherry",
        botanical_name: "Solanum pseudocapsicum",
        type: "Foliage",
        origin: "Central and South America",
        watering: "Every 9 days",
        soil: "Any good-quality, all-purpose potting mix",
        propagation: "Stem cuttings / Seeds",
        height: "1-2 ft / 30-60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40-50%",
    },
    {
        i: 56,
        name: "Juncus Corkscrew Rush",
        botanical_name: 'Juncus effusus "Spiralis"',
        type: "Foliage",
        origin: "Japan",
        watering: "Every 9 days",
        soil: "African violet mix",
        propagation: "Offsets",
        height: "2-3 ft / 60-90 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40-50%",
    },
    {
        i: 57,
        name: "Kentia Palm",
        botanical_name: "Howea forsteriana",
        type: "Foliage",
        origin: "Lord Howe Island (Northeast of Australia)",
        watering: "Every 7-10 days",
        soil: "Peat moss-based potting mix with added horticultural sand for quick drainage",
        propagation: "Seeds",
        height: "8 ft / 2.4 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "40%",
    },
    {
        i: 58,
        name: "Lady Palm",
        botanical_name: "Rhapis excelsa",
        type: "Foliage",
        origin: "Southeast China",
        watering: "Every week",
        soil: "Peat moss based potting mix",
        propagation: "Seeds / Division",
        height: "10 ft / 3 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 59,
        name: "Lucky Bamboo",
        botanical_name: "Dracaena sanderiana",
        type: "Foliage",
        origin: "Africa",
        watering: "Every week",
        soil: "Water / Sandy loam or cactus and succulent potting mix",
        propagation: "Stem cuttings",
        height: "3 ft / 90 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40%",
    },
    {
        i: 60,
        name: "Maidenhair Fern",
        botanical_name: "Adiantum",
        type: "Foliage",
        origin: "Brazil and Venezuela",
        watering: "Every 1-3 days",
        soil: "Combine half potting mix with half peat moss",
        propagation: "Division",
        height: "6-15 in / 15-38 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 61,
        name: "Ming Aralia",
        botanical_name: "Polyscias fruticosa",
        type: "Foliage",
        origin: "Pacific Islands and Southeast Asia",
        watering: "Every week",
        soil: "Peat moss-based potting mix with perlite added for good drainage",
        propagation: "Stem cuttings",
        height: "3 ft / 90 cm",
        temperature: "65-85°F / 18-29°C",
        humidity: "50%",
    },
    {
        i: 62,
        name: "Money Tree Plant",
        botanical_name: "Pachira aquatica",
        type: "Foliage",
        origin: "Wetlands in Central and South America",
        watering: "Every 1-2 weeks",
        soil: "Peat moss-based potting mix with perlite or sand added for good drainage",
        propagation: "Seeds / Stem cuttings",
        height: "10 ft / 3 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 63,
        name: "Monstera Swiss Cheese Vine",
        botanical_name: "Monstera adansonii",
        type: "Foliage",
        origin: "South America",
        watering: "Every week",
        soil: "Mix 1 part peat moss-based mix and 1 part sand or perlite for faster drainage",
        propagation: "Stem cuttings",
        height: "8 ft / 2.4 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 64,
        name: "Moses in the Cradle",
        botanical_name: "Tradescantia spathacea",
        type: "Foliage",
        origin: "Mexico",
        watering: "Every 3 days",
        soil: "Good-quality, all-purpose houseplant potting mix",
        propagation: "Division",
        height: "1-2 ft / 30-60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40%",
    },
    {
        i: 65,
        name: "Muehlenbeckia spp",
        botanical_name: "Muehlenbeckia complexa",
        type: "Foliage",
        origin: "New Zealand",
        watering: "Every week",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "2-3 ft / 60-91 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40%",
    },
    {
        i: 66,
        name: "Nerve Plant",
        botanical_name: "Fittonia verschaffeltii",
        type: "Foliage",
        origin: "Peru",
        watering: "Every 3-4 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "6 in / 15 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "60-70%",
    },
    {
        i: 67,
        name: "Norfolk Island Pine",
        botanical_name: "Araucaria heterophylla",
        type: "Foliage",
        origin: "Norfolk Island",
        watering: "Every 1-2 weeks",
        soil: "Soil-based potting mix",
        propagation: "Seeds",
        height: "6 ft / 1.8 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 68,
        name: "Ornamental Chili Pepper",
        botanical_name: "Capsicum annuum",
        type: "Foliage",
        origin: "South America",
        watering: "Every 9 days",
        soil: "Any good-quality, all-purpose potting mix",
        propagation: "Seeds",
        height: "1 ft / 30 cm",
        temperature: "70-75°F / 21-24°C",
        humidity: "50%",
    },
    {
        i: 69,
        name: "Papyrus Plant",
        botanical_name: "Cyperus papyrus",
        type: "Foliage",
        origin: "Tropical Africa",
        watering: "Every 1-3 days",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Division / Stem cuttings",
        height: "2 ft / 60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "45-50%",
    },
    {
        i: 70,
        name: "Parlor Palm",
        botanical_name: "Chamaedorea elegans",
        type: "Foliage",
        origin: "Mexico and Guatemala",
        watering: "Every week",
        soil: "2 parts peat moss-based potting mix and 1 part sharp sand",
        propagation: "Seeds",
        height: "3-4 ft / 90 cm - 1.2 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 71,
        name: "Peacock Plant",
        botanical_name: "Calathea makoyana",
        type: "Foliage",
        origin: "Brazil",
        watering: "2-3 times a week",
        soil: "Peat moss based potting mix",
        propagation: "Division",
        height: "2 ft / 60 cm",
        temperature: "70-85°F / 21-29°C",
        humidity: "60%",
    },
    {
        i: 72,
        name: "Peperomia",
        botanical_name: "Peperomia caperata",
        type: "Foliage",
        origin: "Brazil",
        watering: "Every 1-2 weeks",
        soil: "Light peat moss potting mix that contains perlite or sand to help drainage",
        propagation: "Leaf / Steam cuttings",
        height: "8 in / 20 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "4-50%",
    },
    {
        i: 73,
        name: "Persian Shield",
        botanical_name: "Strobilanthes dyerianus",
        type: "Foliage",
        origin: "Burma (officially, the Union of Myanmar)",
        watering: "Every 9 days",
        soil: "Any good-quality, all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "2 ft / 60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 74,
        name: "Philodendron Birkin",
        botanical_name: "Philodendron hybrid",
        type: "Foliage",
        origin: "Central and South America",
        watering: "Every week",
        soil: "Peat-moss based potting mix with added perlite to prevent soggy potting mix",
        propagation: "Stem cuttings",
        height: "1 ft / 30 cm",
        temperature: "70-80°F / 21-27°C",
        humidity: "45%",
    },
    {
        i: 75,
        name: "Philodendron Brasil",
        botanical_name: "Philodendron hybrid",
        type: "Foliage",
        origin: "South America",
        watering: "Every 6-7 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "4 ft / 1.2 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "45%",
    },
    {
        i: 76,
        name: "Philodendron Micans",
        botanical_name: 'Philodendron hederaceum "Brasil"',
        type: "Foliage",
        origin: "South America",
        watering: "Every week",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "4 ft / 1.2 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "45%",
    },
    {
        i: 77,
        name: 'Philodendron Prince of Orange',
        botanical_name: "Philodendron hederaceum hybrid",
        type: "Foliage",
        origin: "Central and South America",
        watering: "Every week",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "2 ft / 60 cm",
        temperature: "70-85°F / 21-29°C",
        humidity: "50%",
    },
    {
        i: 78,
        name: "Piggyback Plant",
        botanical_name: "Tolmiea menziesii",
        type: "Foliage",
        origin: "West Coast of North America (From Alaska to Northern California)",
        watering: "Every week",
        soil: "Peat moss-based potting mix",
        propagation: "Leaf cuttings",
        height: "1 ft / 30 cm",
        temperature: "50-75°F / 10-24°C",
        humidity: "50%",
    },
    {
        i: 79,
        name: "Pitcher Plant",
        botanical_name: "Nepenthes hybrids",
        type: "Foliage",
        origin: "Borneo and Malaysia",
        watering: "Every week",
        soil: "Nutrient-poor medium / Mix 1 part peat moss with 1 part perlite or horticultural sand",
        propagation: "Leaf cuttings",
        height: "10 ft / 3 m",
        temperature: "75-85°F/24-29°C",
        humidity: "50-80%",
    },
    {
        i: 80,
        name: "Pleomele",
        botanical_name: "Dracaena reflexa",
        type: "Foliage",
        origin: "Madagascar and other islands in the Indian Ocean",
        watering: "Every 1-2 weeks",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "3 ft / 90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 81,
        name: "Polka Dot Plant",
        botanical_name: "Hypoestes phyllostachya",
        type: "Foliage",
        origin: "Madagascar",
        watering: "Every 4 days",
        soil: "Good-quality, houseplant potting mix",
        propagation: "Seeds / Stem cuttings",
        height: "10 in / 25 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 82,
        name: "Pothos",
        botanical_name: "Epipremnum aureum",
        type: "Foliage",
        origin: "Solomon Islands",
        watering: "Every 1-2 weeks",
        soil: "Good-quality all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "8 ft / 2.4 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "40%",
    },
    {
        i: 83,
        name: "Prayer Plant",
        botanical_name: "Maranta leuconeura",
        type: "Foliage",
        origin: "Brazil",
        watering: "Every 1-2 week",
        soil: "Peat-rich potting mix",
        propagation: "Stem cuttings",
        height: "1 ft / 30 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 84,
        name: "Purple Heart Plant",
        botanical_name: "Tradescantia pallida",
        type: "Foliage",
        origin: "Mexico",
        watering: "Every 7-10 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "2 ft / 60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40%",
    },
    {
        i: 85,
        name: "Purple Passion Plant",
        botanical_name: "Gynura aurantiaca",
        type: "Foliage",
        origin: "Indonesia",
        watering: "Every week",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "2-4 ft / 60 cm - 1.2 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 86,
        name: "Purple Pitcher Plant",
        botanical_name: "Sarracenia purpurea",
        type: "Foliage",
        origin: "East Coast of the US and Southeastern Canada",
        watering: "Every week",
        soil: "Mixture of 1 part sphagnum peat moss and 1 part perlite or horticultural sand",
        propagation: "Division",
        height: "1 ft / 30 cm",
        temperature: "60-70°F / 16-21°C",
        humidity: "50%",
    },
    {
        i: 87,
        name: "Pygmy Date Palm",
        botanical_name: "Phoenix roebelenii",
        type: "Foliage",
        origin: "Southeast Asia",
        watering: "Every 2-3 days",
        soil: "Potting mix that drains well",
        propagation: "Suckers / Seeds",
        height: "6 ft / 1.8 m",
        temperature: "65-85°F / 18-29°C",
        humidity: "50%",
    },
    {
        i: 88,
        name: "Rabbit Foot Fern",
        botanical_name: "Davallia fejeensis",
        type: "Foliage",
        origin: "Fiji",
        watering: "Every week",
        soil: "Any good potting mix that drains well",
        propagation: "Division",
        height: "18 in / 46 cm",
        temperature: "60-75°F / 16-24°C",
        humidity: "50%",
    },
    {
        i: 89,
        name: "Rex Begonia",
        botanical_name: "Begonia rex",
        type: "Foliage",
        origin: "Southeast Asia and India",
        watering: "Every week",
        soil: "African violet potting mix",
        propagation: "Leaf cuttings",
        height: "1 ft / 30 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 90,
        name: "Rosary Vine",
        botanical_name: "Ceropegia woodii",
        type: "Foliage",
        origin: "South Africa",
        watering: "Every 12 days",
        soil: "Mix 1 part good-quality, all-purpose potting mix and 1 part sand or perlite for fast drainage / Cactus potting mix",
        propagation: "Stem cuttings",
        height: "10 ft / 3 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "45%",
    },
    {
        i: 91,
        name: "Rubber Plant",
        botanical_name: "Ficus elastica",
        type: "Foliage",
        origin: "India and Malaysia",
        watering: "Every 1-2 weeks",
        soil: "Peat moss-based potting mix",
        propagation: "Stem cuttings",
        height: "10 ft / 3 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 92,
        name: "Sago Palm",
        botanical_name: "Cycas revoluta",
        type: "Foliage",
        origin: "Japan",
        watering: "1-2 times a week",
        soil: "Cactus potting mix works well for fast drainage",
        propagation: "Seeds / Offsets",
        height: "6 ft / 1.8 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 93,
        name: "Satin Pothos",
        botanical_name: "Scindapsus pictus",
        type: "Foliage",
        origin: "Southeast Asia",
        watering: "Every 1-2 weeks",
        soil: "All-purpose houseplant potting mix",
        propagation: "Stem cuttings",
        height: "3 ft / 90 cm",
        temperature: "65-85°F / 18-29°C",
        humidity: "40-50%",
    },
    {
        i: 94,
        name: "Schefflera",
        botanical_name: "Schefflera spp.",
        type: "Foliage",
        origin: "Australia and Pacific Islands",
        watering: "Every 10 days",
        soil: "Peat moss-based potting mix",
        propagation: "Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "40-50%",
    },
    {
        i: 95,
        name: "Screw Pine",
        botanical_name: "Pandanus veitchii",
        type: "Foliage",
        origin: "Southeast Asia and the Pacific Islands",
        watering: "Every 9 days",
        soil: "Good-quality potting medium with a couple handfuls of horticultural sand mixed in",
        propagation: "Offshoots",
        height: "3 ft / 90 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 96,
        name: "Sensitive Plant",
        botanical_name: "Mimosa pudica",
        type: "Foliage",
        origin: "Central and South Americas",
        watering: "Every 9 days",
        soil: "Peat moss based potting mix with added perlite or horticultural sand",
        propagation: "Seeds",
        height: "3 ft / 90 cm",
        temperature: "70-75°F / 21-24°C",
        humidity: "50%",
    },
    {
        i: 97,
        name: "Snow Bush",
        botanical_name: "Breynia nivosa",
        type: "Foliage",
        origin: "Tropical Asia, Pacific Islands and Tropical Australia, U.S.",
        watering: "Every 7-10",
        soil: "Good-quality houseplant potting mix",
        propagation: "Stem cuttings",
        height: "3 ft / 90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 98,
        name: "Spider Plant",
        botanical_name: "Chlorophytum comosum",
        type: "Foliage",
        origin: "South Pacific and South Africa",
        watering: "Every week",
        soil: "African violet mix",
        propagation: "Plantlets",
        height: "3 ft / 90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "45%",
    },
    {
        i: 99,
        name: "Split Leaf Philodendron",
        botanical_name: "Philodendron bipinnatifidum",
        type: "Foliage",
        origin: "Brazil",
        watering: "Every 7-10 days",
        soil: "Peat moss-based potting mix",
        propagation: "Division",
        height: "6 ft / 1.8 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "40%",
    },
    {
        i: 100,
        name: "Staghorn Fern",
        botanical_name: "Platycerium bifurcatum",
        type: "Foliage",
        origin: "Tropical Australia",
        watering: "Every 1-2 weeks",
        soil: "Sphagnum moss or medium specially made for epiphytes such as bromeliad or orchid mix",
        propagation: "Offsets",
        height: "3 ft / 90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 101,
        name: "Strawberry Begonia",
        botanical_name: "Saxifraga stolonifera",
        type: "Foliage",
        origin: "East Asia",
        watering: "Every 9 days",
        soil: "Any good-quality, all-purpose potting mix",
        propagation: "Runners",
        height: "12 in / 30 cm",
        temperature: "50-75°F / 10-24°C",
        humidity: "40-50%",
    },
    {
        i: 102,
        name: "Stromanthe",
        botanical_name: "Stromanthe sanguinea",
        type: "Foliage",
        origin: "Brazil",
        watering: "Every week",
        soil: "Peat moss-based potting mix or other soilless potting medium",
        propagation: "Division",
        height: "3 ft / 90 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 103,
        name: "Swedish Ivy",
        botanical_name: "Plectranthus species",
        type: "Foliage",
        origin: "Northern Australia, Pacific Islands",
        watering: "Every week",
        soil: "Peat moss-based potting mix",
        propagation: "Stem cuttings",
        height: "3 ft / 90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "45%",
    },
    {
        i: 104,
        name: "Sweet Potato Vine",
        botanical_name: "Ipomea batatas",
        type: "Foliage",
        origin: "Central America",
        watering: "Every 9 days",
        soil: "All-purpose potting mix",
        propagation: "Stem cuttings",
        height: "12 in / 30 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40%",
    },
    {
        i: 105,
        name: "Swiss Cheese Plant",
        botanical_name: "Monstera deliciosa",
        type: "Foliage",
        origin: "Southern Mexico and Guatemala",
        watering: "Every 9 days",
        soil: "Mix 1 part peat moss-based mix and 1 part sand or perlite for good drainage",
        propagation: "Stem cuttings",
        height: "10 ft / 3 m",
        temperature: "65-85°F / 18-29°C",
        humidity: "40%",
    },
    {
        i: 106,
        name: "Ti Plant",
        botanical_name: "Cordyline terminalis",
        type: "Foliage",
        origin: "Southeast Asia and the Pacific Islands",
        watering: "Every week",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "3-5 ft / 90 cm - 1.5 m",
        temperature: "65-85°F / 18-29°C",
        humidity: "50-60%",
    },
    {
        i: 107,
        name: "Triangle Ficus",
        botanical_name: "Ficus triangularis",
        type: "Foliage",
        origin: "Southeast Asia ",
        watering: "1-2 times a week",
        soil: "Soilless potting mix",
        propagation: "Stem cuttings",
        height: "4-6 ft / 1.2-1.8 m",
        temperature: "65-85°F / 18-29°C",
        humidity: "70%",
    },
    {
        i: 108,
        name: "Venus Fly Trap",
        botanical_name: "Dionaea muscipula",
        type: "Foliage",
        origin: "North and South Carolina",
        watering: "Every 2-4 days",
        soil: "Nutrient-poor soil / Sphagnum moss or mix 1 part peat moss with 1 part perlite",
        propagation: "Division / Seeds",
        height: "3-10 in / 8-25 cm",
        temperature: "60-75°F / 16-24°C",
        humidity: "50%",
    },
    {
        i: 109,
        name: "Watermelon Peperomia",
        botanical_name: "Peperomia argyreia",
        type: "Foliage",
        origin: "Brazil",
        watering: "Every 5-7 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "10 in / 25 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 110,
        name: "Weeping Fig",
        botanical_name: "Ficus benjamina",
        type: "Foliage",
        origin: "Southeast Asia and Northern Australia",
        watering: "Every week",
        soil: "Soilless potting mix or any that drains well",
        propagation: "Stem cuttings",
        height: "10 ft / 3 m",
        temperature: "65-85°F / 18-29°C",
        humidity: "40%",
    },
    {
        i: 111,
        name: "Windmill Palm Tree",
        botanical_name: "Trachycarpus fortunei",
        type: "Foliage",
        origin: "Southeast Asia",
        watering: "Every week",
        soil: "Mix 1 part sand to 3 parts African violet potting mix",
        propagation: "Seeds",
        height: "8 ft / 2.4 m",
        temperature: "65-75°F / 18-24°C ",
        humidity: "50%",
    },
    {
        i: 112,
        name: "Zebra Plant",
        botanical_name: "Aphelandra squarrosa",
        type: "Foliage",
        origin: "Brazil",
        watering: "Every 9 days",
        soil: "African violet mix",
        propagation: "Stem cuttings",
        height: "1-2 ft / 30-60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50-70%",
    },
    {
        i: 113,
        name: "ZZ Plant",
        botanical_name: "Zamioculcas zamiifolia",
        type: "Foliage",
        origin: "East Africa",
        watering: "Every 2-3 weeks",
        soil: "Mix 1 part good-quality all-purpose potting mix and 1 part horticultural sand or perlite / Cactus potting mix",
        propagation: "Division / Leaf cuttings",
        height: "3 ft / 90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 114,
        name: "Achimenes",
        botanical_name: "Achimenes hybrids",
        type: "Flowering",
        origin: "Central America",
        watering: "Every 9 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "1-2 ft / 30-60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40-50%",
    },
    {
        i: 115,
        name: "African Lily",
        botanical_name: "Agapanthus africanus",
        type: "Flowering",
        origin: "South Africa",
        watering: "Every 9 days",
        soil: "Good-quality, all-purpose potting mix ",
        propagation: "Division / Seeds",
        height: "2-3 ft / 60-90 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40-50%",
    },
    {
        i: 116,
        name: "African Violet",
        botanical_name: "Saintpaulia",
        type: "Flowering",
        origin: "Eastern Africa",
        watering: "Every week",
        soil: "African violet potting mix",
        propagation: "Leaf cuttings",
        height: "6 in / 15 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50-60%",
    },
    {
        i: 117,
        name: "Air Plant",
        botanical_name: "Tillandsia ionantha",
        type: "Flowering",
        origin: "Central and South America",
        watering: "Every week",
        soil: "None needed",
        propagation: "Offsets",
        height: "6-12 in / 15-30 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 118,
        name: "Amaryllis",
        botanical_name: "Hippeastrum hybrids",
        type: "Flowering",
        origin: "South America",
        watering: "Every week",
        soil: "Any good-quality potting mix.",
        propagation: "Offsets",
        height: "12-24 in / 30-60 cm",
        temperature: "55-70°F / 13-21°C",
        humidity: "40%",
    },
    {
        i: 119,
        name: "Amazon Lily",
        botanical_name: "Eucharis x grandiflora",
        type: "Flowering",
        origin: "Colombia and Peru",
        watering: "Every 9 days",
        soil: "Rich, humusy potting mix amended with coarse sand for good drainage",
        propagation: "Offsets",
        height: "2 ft / 60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40-50%",
    },
    {
        i: 120,
        name: "Angel Trumpet Plant",
        botanical_name: "Brugmansia x candida",
        type: "Flowering",
        origin: "Subtropical South America",
        watering: "Every 9 days",
        soil: "Good-quality potting mix specially made for container plants",
        propagation: "Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 121,
        name: "Angel Wing Begonia",
        botanical_name: "Begonia x corallina",
        type: "Flowering",
        origin: "South America",
        watering: "Every 9 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "1-3 ft / 30-90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "25-50%",
    },
    {
        i: 122,
        name: "Anthurium Plant",
        botanical_name: "Anthurium andraeanum",
        type: "Flowering",
        origin: "Colombia",
        watering: "Every week",
        soil: "Peat moss based potting mix with added perlite / African violet potting mix",
        propagation: "Division",
        height: "12-18 in / 30-45 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 123,
        name: "Azalea",
        botanical_name: "Rhododendron simsii",
        type: "Flowering",
        origin: "Asia",
        watering: "1-2 times a week",
        soil: "Acidic potting mix (4.5 to 6.0 pH) / Peat-based (lime free) potting mix",
        propagation: "Stem cuttings",
        height: "2 ft / 60 cm",
        temperature: "60-70°F / 16-21°C",
        humidity: "40%",
    },
    {
        i: 124,
        name: "Banana Shrub",
        botanical_name: "Michelia figo",
        type: "Flowering",
        origin: "China",
        watering: "Every week",
        soil: "African violet mix",
        propagation: "Stem cuttings",
        height: "6-10 ft / 1.8-3 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 125,
        name: "Bat Flower",
        botanical_name: "Tacca chantrieri",
        type: "Flowering",
        origin: "Yunnan Province, China",
        watering: "Every week",
        soil: "Peat-moss based, African violet potting mix",
        propagation: "Division / Seeds",
        height: "2 ft / 60 cm",
        temperature: "65-70°F / 18-21°C",
        humidity: "50-70%",
    },
    {
        i: 126,
        name: "Begonia",
        botanical_name: "Begonia x hiemalis",
        type: "Flowering",
        origin: "South and Central America, Africa, Southern Asia",
        watering: "Every 2-4 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings",
        height: "12-18 in / 30-45 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 127,
        name: "Bird of Paradise",
        botanical_name: "Strelitzia reginae",
        type: "Flowering",
        origin: "South Africa ",
        watering: "Every 1-2 weeks",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Seeds / Division",
        height: "6 ft / 1.8 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 128,
        name: "Bleeding Heart Vine",
        botanical_name: "Clerodendrum thomsoniae",
        type: "Flowering",
        origin: "Tropical West Africa",
        watering: "Every week",
        soil: "Good-quality potting mix",
        propagation: "Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "65-85°F / 18-29°C",
        humidity: "60%",
    },
    {
        i: 129,
        name: "Blood Lily",
        botanical_name: "Scadoxus multiflorus",
        type: "Flowering",
        origin: "Tropical South Africa ",
        watering: "Every 2-3 days",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Offsets",
        height: "12-24 in / 30-60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40%",
    },
    {
        i: 130,
        name: "Bottle Brush Plant",
        botanical_name: "Callistemon citrinus",
        type: "Flowering",
        origin: "Australia",
        watering: "Every week",
        soil: "2 parts all-purpose potting mix and 1 part horticultural sand",
        propagation: "Stem cuttings / Seeds",
        height: "4 ft / 1.2 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 131,
        name: "Bougainvillea Plant",
        botanical_name: "Bougainvillea glabra",
        type: "Flowering",
        origin: "Brazil",
        watering: "Every 9 days",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "10 ft / 3 m",
        temperature: "60-80°F / 16-27°C",
        humidity: "50%",
    },
    {
        i: 132,
        name: "Brazilian Plume",
        botanical_name: "Justicia carnea",
        type: "Flowering",
        origin: "Brazil",
        watering: "Every 9 days",
        soil: "Good-quality all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "4 ft / 1.2 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 133,
        name: "Camellia",
        botanical_name: "Camellia japonica",
        type: "Flowering",
        origin: "Japan, China, Korea",
        watering: "Every 3 days",
        soil: "Acidic medium, lime-free peat moss-based mix",
        propagation: "Stem cuttings",
        height: "10 ft / 3 m",
        temperature: "45-60°F / 7-16°C",
        humidity: "50%",
    },
    {
        i: 134,
        name: "Campanula Flowers",
        botanical_name: "Campanula isophylla",
        type: "Flowering",
        origin: "Northern Italy",
        watering: "Every week",
        soil: "Any good-quality houseplant potting mix",
        propagation: "Stem cuttings / Seeds",
        height: "1 ft / 30 cm",
        temperature: "45-65°F / 7-18°C",
        humidity: "40%",
    },
    {
        i: 135,
        name: "Candy Corn Plant",
        botanical_name: "Manettia inflata",
        type: "Flowering",
        origin: "South America",
        watering: "Every 7-10 days",
        soil: "Well-aerated potting mixture",
        propagation: "Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "45%",
    },
    {
        i: 136,
        name: "Cape Primrose",
        botanical_name: "Streptocarpus hybrids",
        type: "Flowering",
        origin: "South Africa",
        watering: "Every 9 days",
        soil: "African violet potting mix",
        propagation: "Leaf cuttings / Division / Seeds",
        height: "1 ft / 30 cm",
        temperature: "60-70°F / 16-21°C",
        humidity: "50%",
    },
    {
        i: 137,
        name: "Celosia Plumosa",
        botanical_name: "Celosia argentea var. plumosa",
        type: "Flowering",
        origin: "Tropical Asia",
        watering: "Every 9 days",
        soil: "Peat moss-based potting mix",
        propagation: "Seeds",
        height: "6-24 in / 15-60 cm",
        temperature: "70-80°F / 21-27°C",
        humidity: "40%",
    },
    {
        i: 138,
        name: "Cigar Plant",
        botanical_name: "Cuphea ignea",
        type: "Flowering",
        origin: "Mexico",
        watering: "Every 9 days",
        soil: "All-purpose, good-quality potting mix",
        propagation: "Stem cuttings",
        height: "2 ft / 60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "45%",
    },
    {
        i: 139,
        name: "Cineraria Flowers",
        botanical_name: "Senecio hybrids",
        type: "Flowering",
        origin: "Canary Island",
        watering: "Every 9 days",
        soil: "Peat-moss based potting mix",
        propagation: "Seeds",
        height: "1-2 ft / 30-60 cm",
        temperature: "50-65°F / 10-18°C",
        humidity: "40%",
    },
    {
        i: 140,
        name: "Clivia Lily",
        botanical_name: "Clivia miniata",
        type: "Flowering",
        origin: "South Africa",
        watering: "Every week",
        soil: "Good-quality, peat-based potting mix",
        propagation: "Division",
        height: "2 ft / 60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "45%",
    },
    {
        i: 141,
        name: "Coral Berry",
        botanical_name: "Ardisia crenata",
        type: "Flowering",
        origin: "East Asia",
        watering: "Every 7-10 days",
        soil: "Soil-based potting mix",
        propagation: "Seeds / Stem cuttings",
        height: "3 ft / 90 cm",
        temperature: "45-65°F / 7-18°C",
        humidity: "50-60%",
    },
    {
        i: 142,
        name: "Crocus",
        botanical_name: "Crocus hybrids",
        type: "Flowering",
        origin: "Europe, North Africa and Asia",
        watering: "Every 7-14 days",
        soil: "Any good-quality potting mix",
        propagation: "Bulbs",
        height: "8 in / 20 cm",
        temperature: "40-60°F / 6-16°C",
        humidity: "40%",
    },
    {
        i: 143,
        name: "Cyclamen",
        botanical_name: "Cyclamen persicum",
        type: "Flowering",
        origin: "Southern Europe and the Middle East",
        watering: "Every week",
        soil: "Good-quality all-purpose potting mix",
        propagation: "Seeds",
        height: "6-12 ft / 15-30 cm",
        temperature: "55-70°F / 13-21°C",
        humidity: "40-50%",
    },
    {
        i: 144,
        name: "Daffodils",
        botanical_name: "Narcissus spp.",
        type: "Flowering",
        origin: "Europe",
        watering: "Every week",
        soil: "Peat moss-based potting mix",
        propagation: "Bulbs",
        height: "6-18 in / 15-46 cm",
        temperature: "60°F / 16°C",
        humidity: "40-50%",
    },
    {
        i: 145,
        name: "Dragon Wing Begonia",
        botanical_name: "Begonia hybrids",
        type: "Flowering",
        origin: "South America",
        watering: "Every 2-4 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings / Seeds",
        height: "2 ft / 60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50-60%",
    },
    {
        i: 146,
        name: "Dutch Iris",
        botanical_name: "Iridaceae x hollandica",
        type: "Flowering",
        origin: "Netherlands",
        watering: "Every week",
        soil: "Any good potting mix",
        propagation: "Bulbs",
        height: "2 ft / 60 cm",
        temperature: "60-65°F / 10-18°C",
        humidity: "40%",
    },
    {
        i: 147,
        name: "Dwarf Chenille Plant",
        botanical_name: "Acalypha pendula",
        type: "Flowering",
        origin: "Java and New Guinea",
        watering: "Every 3-7 days",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "1 ft / 30 cm",
        temperature: "65-85°F/18-29°C",
        humidity: "50-60%",
    },
    {
        i: 148,
        name: "Dwarf Irises",
        botanical_name: "Iris reticulata",
        type: "Flowering",
        origin: "High mountains of Iran and Turkey",
        watering: "Every week",
        soil: "All-purpose potting mix",
        propagation: "Bulbs",
        height: "6-10 in / 15-25 cm",
        temperature: "60-65°F / 10-18°C",
        humidity: "40%",
    },
    {
        i: 149,
        name: "Easter Lily",
        botanical_name: "Lilium longiflorum",
        type: "Flowering",
        origin: "Japan",
        watering: "Every 2-3 days",
        soil: "Peat moss based potting mix",
        propagation: "Bulbs",
        height: "3 ft / 90 cm",
        temperature: "60-65° / 16-18°C",
        humidity: "40%",
    },
    {
        i: 150,
        name: "Firecracker Flower",
        botanical_name: "Crossandra infundibuliformis",
        type: "Flowering",
        origin: "Southern India and Sri Lanka",
        watering: "1-2 times a week",
        soil: "All-purpose houseplant potting mix",
        propagation: "Stem cuttings / Seeds",
        height: "16 in / 40 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 151,
        name: "Flame Violet",
        botanical_name: "Episcia cupreata",
        type: "Flowering",
        origin: "Colombia and Venezuela",
        watering: "Every 9 days",
        soil: "African violet potting mix",
        propagation: "Leaf cuttings",
        height: "4 ft / 1.2 m",
        temperature: "55-65°F / 13-18°C",
        humidity: "50%",
    },
    {
        i: 152,
        name: "Flamingo Flower",
        botanical_name: "Anthurium scherzerianum",
        type: "Flowering",
        origin: "Costa Rica",
        watering: "Every week",
        soil: "African violet potting mix",
        propagation: "Division",
        height: "12-18 in / 30-45 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 153,
        name: "Florist Chrysanthemum",
        botanical_name: "Chrysanthemum morifolium",
        type: "Flowering",
        origin: "China",
        watering: "1-2 times a week",
        soil: "Peat moss based potting mix",
        propagation: "Stem cuttings",
        height: "1-2 ft / 30-60 cm",
        temperature: "55-65°F / 13-18°C",
        humidity: "40-50%",
    },
    {
        i: 154,
        name: "Flowering Maple",
        botanical_name: "Abutilon hybrids",
        type: "Flowering",
        origin: "Brazil",
        watering: "Every 9 days",
        soil: "Peat moss-based potting mix",
        propagation: "Stem cuttings",
        height: "10 ft / 3 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "40-50%",
    },
    {
        i: 155,
        name: "Freesia Flower",
        botanical_name: "Freesia hybrids",
        type: "Flowering",
        origin: "South Africa",
        watering: "Every week",
        soil: "Good-quality, all-purpose potting mix with horticultural sand",
        propagation: "Offsets",
        height: "18 in / 46 cm",
        temperature: "60-65°F / 16-18°C",
        humidity: "40-50%",
    },
    {
        i: 156,
        name: "Fuchsia Plant",
        botanical_name: "Fuchsia hybrids",
        type: "Flowering",
        origin: "Mexico, Argentina and Chile",
        watering: "2-3 times a week",
        soil: "All-purpose good-quality potting mix",
        propagation: "Stem cuttings",
        height: "3 ft / 90 cm",
        temperature: "50-55°F / 10-13°C",
        humidity: "40%",
    },
    {
        i: 157,
        name: "Gardenia",
        botanical_name: "Gardenia jasminoides",
        type: "Flowering",
        origin: "China",
        watering: "Every week",
        soil: "Lime-free acidic potting mix, such as a peat-moss based mix",
        propagation: "Stem cuttings",
        height: "1-3 ft / 30-90 cm",
        temperature: "60-75°F / 16-24°C",
        humidity: "60%",
    },
    {
        i: 158,
        name: "Geranium",
        botanical_name: "Pelargonium x hortorum",
        type: "Flowering",
        origin: "South Africa",
        watering: "Every 2-5 days",
        soil: "Peat moss-based soilless mix",
        propagation: "Stem cuttings",
        height: "1-3 ft / 30-90 cm",
        temperature: "65-75°F/18-24°C",
        humidity: "40%",
    },
    {
        i: 159,
        name: "Gerbera Daisy",
        botanical_name: "Gerbera jamesonii",
        type: "Flowering",
        origin: "South Africa",
        watering: "Every week",
        soil: "African violet potting mix",
        propagation: "Division / Seeds",
        height: "2 ft / 60 cm",
        temperature: "55-75°F / 13-24°C",
        humidity: "40%",
    },
    {
        i: 160,
        name: "Glory Lily",
        botanical_name: "Gloriosa superba",
        type: "Flowering",
        origin: "Tropical Africa",
        watering: "1-2 times a week",
        soil: "Peat moss based potting mix",
        propagation: "Offsets / Seeds",
        height: "4 ft / 1.2 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 161,
        name: "Gloxinia",
        botanical_name: "Sinningia speciosa hybrids",
        type: "Flowering",
        origin: "Brazil",
        watering: "Every 2-3 days",
        soil: "African violet potting mix",
        propagation: "Seeds / Leaf cuttings / Division",
        height: "8 in / 20 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "50%",
    },
    {
        i: 162,
        name: "Grape Hyacinths",
        botanical_name: "Muscari spp.",
        type: "Flowering",
        origin: "Western Asia",
        watering: "1-2 times a week",
        soil: "All-purpose good-quality potting mix / Water",
        propagation: "Offsets",
        height: "4-8 in / 10-20 cm",
        temperature: "40-65°F / 4-18°C",
        humidity: "40%",
    },
    {
        i: 163,
        name: "Heliconia",
        botanical_name: "Heliconia psittacorum",
        type: "Flowering",
        origin: "Brazil",
        watering: "2-3 times a week",
        soil: "African violet potting mix",
        propagation: "Division",
        height: "3-4 ft / 0.9-1.2 m",
        temperature: "65-80°F / 18-27°C",
        humidity: "50-60%",
    },
    {
        i: 164,
        name: "Hellebore",
        botanical_name: "Helleborus niger",
        type: "Flowering",
        origin: "Mountainous regions of Europe, including Switzerland, southern Germany, Austria and northern Italy",
        watering: "Every week",
        soil: "Neutral (pH 7) to alkaline (up to pH 9) potting mix",
        propagation: "Division",
        height: "1 ft / 30 cm",
        temperature: "45-65°F / 7-18°C ",
        humidity: "40%",
    },
    {
        i: 165,
        name: "Hibiscus",
        botanical_name: "Hibiscus rosa-sinensis",
        type: "Flowering",
        origin: "China",
        watering: "2 times a week",
        soil: "All-purpose mix wuth a couple handfuls of perlite",
        propagation: "Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "65-85°F / 18-29°C",
        humidity: "50%",
    },
    {
        i: 166,
        name: "Hyacinth Flower",
        botanical_name: "Hyacinthus orientalis hybrids",
        type: "Flowering",
        origin: "Turkey",
        watering: "Every 2-3 days",
        soil: "Good-quality, all-purpose potting mix / Water",
        propagation: "Bulbs",
        height: "8-12 ft / 20-30 cm",
        temperature: "45-65°F / 7-18°C",
        humidity: "40%",
    },
    {
        i: 167,
        name: "Hydrangea",
        botanical_name: "Hydrangea macrophylla",
        type: "Flowering",
        origin: "Japan",
        watering: "2-3 times a week",
        soil: "Peat-based acidic lime-free soil for blue varieties. Alkaline soil for pink",
        propagation: "Stem cuttings",
        height: "2 ft / 60 cm",
        temperature: "60°F / 16°C",
        humidity: "40-45%",
    },
    {
        i: 168,
        name: "Ivy Geranium",
        botanical_name: "Pelargonium peltatum",
        type: "Flowering",
        origin: "South Africa",
        watering: "Every 7-9 days",
        soil: "Peat moss-based soilless mix",
        propagation: "Stem cuttings / Seeds",
        height: "3 ft / 90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40-50%",
    },
    {
        i: 169,
        name: "Jasmine Plant",
        botanical_name: "Jasminum polyanthum",
        type: "Flowering",
        origin: "China",
        watering: "Every week",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Stem cuttings",
        height: "10 ft / 3 m",
        temperature: "65-75°F / 18-24°C",
        humidity: "40-50%",
    },
    {
        i: 170,
        name: "Lily of the Valley",
        botanical_name: "Convallaria majalis",
        type: "Flowering",
        origin: "European and Asian woodlands",
        watering: "Every week",
        soil: "African violet potting mix",
        propagation: "Division / Seeds",
        height: "10 in / 25 cm",
        temperature: "60-70°F / 16-21°C",
        humidity: "40%",
    },
    {
        i: 171,
        name: "Miniature Roses",
        botanical_name: "Rosa chinensis hybrids",
        type: "Flowering",
        origin: "China",
        watering: "Every week",
        soil: "Any good potting mix with neutral pH (pH 7)",
        propagation: "Stem cuttings",
        height: "2 ft / 60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40-50%",
    },
    {
        i: 172,
        name: "Mona Lavender",
        botanical_name: "Plectranthus hybrid",
        type: "Flowering",
        origin: "Tropical South Africa",
        watering: "Every 2-3 days",
        soil: "African violet potting mix",
        propagation: "Stem cuttings / Seeds",
        height: "2 ft / 60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40-50%",
    },
    {
        i: 173,
        name: "Oleander Plant",
        botanical_name: "Nerium oleander",
        type: "Flowering",
        origin: "The Mediterranean Region",
        watering: "Every 3 days",
        soil: "8 parts all-purpose potting mix, 1 part sand, 1 part perlite",
        propagation: "Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "70-85°F / 21-29°C",
        humidity: "40%",
    },
    {
        i: 174,
        name: "Pansy Plants",
        botanical_name: "Viola x wittrockiana",
        type: "Flowering",
        origin: "England",
        watering: "Every week",
        soil: "Any good-quality, all-purpose potting mix",
        propagation: "Seeds",
        height: "8 in / 20 cm",
        temperature: "60-75°F / 16-24°C",
        humidity: "40-50%",
    },
    {
        i: 175,
        name: "Peace Lily or Spatheflower",
        botanical_name: "Spathiphyllum",
        type: "Flowering",
        origin: "South America",
        watering: "Every week",
        soil: "Peat moss-based potting mix",
        propagation: "Division",
        height: "3 ft / 90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 176,
        name: "Periwinkle Flower",
        botanical_name: "Catharanthus roseus",
        type: "Flowering",
        origin: "Madagascar",
        watering: "Every week",
        soil: "All-purpose mix with little perlite",
        propagation: "Seeds",
        height: "1 ft / 30 cm",
        temperature: "65-85°F / 18-29°C",
        humidity: "50%",
    },
    {
        i: 177,
        name: "Pineapple Lily",
        botanical_name: "Eucomis comosa",
        type: "Flowering",
        origin: "South Africa",
        watering: "2-3 times a week",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Bulbs",
        height: "2 ft / 60 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40-50%",
    },
    {
        i: 178,
        name: "Pink Calla Lily",
        botanical_name: "Zantedeschia rehmannii",
        type: "Flowering",
        origin: "South Africa",
        watering: "Every week",
        soil: "African violet potting",
        propagation: "Rhizomes",
        height: "12-16 in / 30-40 cm",
        temperature: "70-85°F / 21-29°C",
        humidity: "40%",
    },
    {
        i: 179,
        name: "Pink Quill",
        botanical_name: "Tillandsia cyanea",
        type: "Flowering",
        origin: "Ecuador",
        watering: "2-3 times a week",
        soil: "Orchid mix for bromeliads",
        propagation: "Offsets",
        height: "1 ft / 30 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "45%",
    },
    {
        i: 180,
        name: "Poinsettia",
        botanical_name: "Euphorbia pulcherrima",
        type: "Flowering",
        origin: "Mexico and Central America",
        watering: "Every 7-10 days",
        soil: "Peat moss based potting mix",
        propagation: "Stem cuttings",
        height: "6-36 in / 15-90 cm",
        temperature: "60-75°F / 15-24°C",
        humidity: "40%",
    },
    {
        i: 181,
        name: "Primrose Flowers",
        botanical_name: "Primula hybrids",
        type: "Flowering",
        origin: "England, Germany and China",
        watering: "2-3 times a week",
        soil: "African violet mix",
        propagation: "Seeds",
        height: "8-12 in / 20-30 cm",
        temperature: "50-65°F / 10-18°C",
        humidity: "40-60%",
    },
    {
        i: 182,
        name: "Purple Shamrock",
        botanical_name: "Oxalis regnellii",
        type: "Flowering",
        origin: "Brazil",
        watering: "Every 1-2 weeks",
        soil: "Any good potting mix",
        propagation: "Division",
        height: "6-12 in / 15-30 cm",
        temperature: "55-65°F / 13-18°C",
        humidity: "50%",
    },
    {
        i: 183,
        name: "Red Spider Lily",
        botanical_name: "Lycoris radiata",
        type: "Flowering",
        origin: "China",
        watering: "Every week",
        soil: "Peat moss based potting mix",
        propagation: "Bulbs",
        height: "2 ft / 60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40-50%",
    },
    {
        i: 184,
        name: "Scarlet Star",
        botanical_name: "Guzmania lingulata",
        type: "Flowering",
        origin: "Central and South America",
        watering: "Every week",
        soil: "Bromeliad / Orchid potting mix",
        propagation: "Offsets",
        height: "1 ft / 30 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "50%",
    },
    {
        i: 185,
        name: "Scented Geranium",
        botanical_name: "Pelargonium species and hybrids",
        type: "Flowering",
        origin: "South Africa",
        watering: "Every 9 days",
        soil: "Peat-based soilless mix",
        propagation: "Stem cuttings / Seeds",
        height: "12-18 in / 30-45 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 186,
        name: "Tulips",
        botanical_name: "Tulipa hybrids",
        type: "Flowering",
        origin: "Asia",
        watering: "Every week",
        soil: "Good-quality, all-purpose potting mix",
        propagation: "Bulbs",
        height: "1-2 ft / 30-60 cm",
        temperature: "60°F / 16°C",
        humidity: "40-50%",
    },
    {
        i: 187,
        name: "Aloe Vera",
        botanical_name: "Aloe barbadensis",
        type: "Succulents",
        origin: "Northeast Africa",
        watering: "Every 2-3 weeks",
        soil: "Cactus potting mix",
        propagation: "Offsets",
        height: "1-2 ft / 30-60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 188,
        name: "Blue Agave",
        botanical_name: "Agave parryi",
        type: "Succulents",
        origin: "Southwestern U.S. and Mexico",
        watering: "Every 2-4 weeks",
        soil: "Cactus potting mix",
        propagation: "Offsets",
        height: "1 ft / 30 cm",
        temperature: "70-90°F / 21-32°C",
        humidity: "40%",
    },
    {
        i: 189,
        name: "Cactus",
        botanical_name: "Cactaceae family",
        type: "Succulents",
        origin: "Southwestern U.S., Mexico and South America",
        watering: "Every 1-4 weeks",
        soil: "Cactus potting mix",
        propagation: "Offsets",
        height: "3 ft / 90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 190,
        name: "Christmas Cactus",
        botanical_name: "Schlumbergera hybrids",
        type: "Succulents",
        origin: "Brazil",
        watering: "Every 1-2 weeks",
        soil: "Peat moss-based potting mix and fine-grade fir bark",
        propagation: "Stem cuttings",
        height: "2 ft / 60 cm",
        temperature: "60-75°F/16-24°C",
        humidity: "50%",
    },
    {
        i: 191,
        name: "Cylindrical Snake Plant",
        botanical_name: "Sansevieria cylindrica",
        type: "Succulents",
        origin: "South Africa",
        watering: "Every 1-2 weeks",
        soil: "Cactus potting mix",
        propagation: "Division",
        height: "2 ft / 60 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 192,
        name: "Donkey's Tail",
        botanical_name: "Sedum morganianum",
        type: "Succulents",
        origin: "Mexico",
        watering: "Every 2 weeks",
        soil: "Cactus potting mix",
        propagation: "Stem cuttings",
        height: "2-3 ft / 60-90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 193,
        name: "Echeveria",
        botanical_name: "Echeveria species",
        type: "Succulents",
        origin: "Southwestern U.S. and Mexico",
        watering: "Every 1-2 weeks",
        soil: "Cactus potting mix",
        propagation: "Offsets / Leaf cuttings",
        height: "2-4 in / 5-10 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40%",
    },
    {
        i: 194,
        name: "Flaming Katy",
        botanical_name: "Kalanchoe blossfeldiana",
        type: "Succulents",
        origin: "Madagascar",
        watering: "Every 1-3 weeks",
        soil: "All-purpose potting mix and horticultural sand or perlite",
        propagation: "Stem cuttings",
        height: "8-15 in / 20-38 cm",
        temperature: "65-80°F / 18-27°C",
        humidity: "40%",
    },
    {
        i: 195,
        name: "Haworthia",
        botanical_name: "Haworthia species",
        type: "Succulents",
        origin: "South Africa",
        watering: "Every 2-3 weeks",
        soil: "Cactus potting mix",
        propagation: "Offsets",
        height: "3-6 in/ 7.5-15 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 196,
        name: "Jade Plant",
        botanical_name: "Crassula ovata",
        type: "Succulents",
        origin: "South Africa",
        watering: "Every 2-3 weeks",
        soil: "2 parts peat moss-based potting mix and 1 part horticultural sand or perlite",
        propagation: "Leaf cuttings",
        height: "1-3 ft / 30-90 cm",
        temperature: "65-75°F / 18-24°C",
        humidity: "40%",
    },
    {
        i: 197,
        name: "Mistletoe Cactus",
        botanical_name: "Rhipsalis baccifera",
        type: "Succulents",
        origin: "Brazil and Peru",
        watering: "Every 12 days",
        soil: "Mix 1 part peat moss-based potting mix and 1 part fine-grade fir bark",
        propagation: "Stem cuttings",
        height: "6 ft / 1.8 m",
        temperature: "70-75°F / 21-24°C",
        humidity: "50%",
    },
    {
        i: 198,
        name: "Paddle Plant",
        botanical_name: "Kalanchoe thyrsiflora",
        type: "Succulents",
        origin: "South Africa",
        watering: "Every 12 days",
        soil: "Cactus potting mix",
        propagation: "Leaf cuttings / Seeds",
        height: "2 ft / 60 cm",
        temperature: "65-80°F / 18-26°C",
        humidity: "40%",
    },
]
export default houseplantList;